spring.application.name=Academi-Gymraeg-Group-Project
spring.datasource.url=jdbc:mysql://mysql.cs.bangor.ac.uk/bcd23dfg?serverTimezone=Europe/London
spring.datasource.username=bcd23dfg
spring.datasource.password= 1da0dc9389
spring.jpa.hibernate.ddl-auto=update