spring.application.name=AcademiCymraeg
spring.datasource.url=jdbc:mysql://mysql.cs.bangor.ac.uk/sml23gsd?serverTimezone=Europe/London
spring.datasource.username=sml23gsd
spring.datasource.password=5acb9a6673
spring.jpa.hibernate.ddl-auto=update